{
 "title": "Tesla Metrics V2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "vehicle_name",
    "label": "Vehicle",
    "query": "show tag values from drive_state with key = display_name"
   },
   { "name": "rangeunit", "query": "km,mi" },
   { "name": "rangefactor", "query": "1.60934,1.0" },
   { "name": "tempfactor", "label": "Temperature Factor C,F", "query": "*1,* 9/5+32" },
   { "name": "tempunit", "label": "Termperature Unit (°C or °F)", "query": "°C,°F" }
  ]
 },
 "panels": [
  {
   "title": "Geolocation $vehicle_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "vehicle_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Elevation",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Elevation MSL",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "drive_state",
       "select": [
        [
         { "params": [ "elevation" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Geolocation",
     "type": "pr0ps-trackmap-panel",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "drive_state",
       "select": [
        [
         { "params": [ "native_latitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "drive_state",
       "select": [
        [
         { "params": [ "native_longitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Driving $vehicle_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Vehicle Speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT last(\"speed\") * $rangefactor FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/)",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "speed" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "Speed" }
   ],
   "targets": [
    {
     "alias": "speed",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "SELECT mean(\"speed\") * $rangefactor FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/ ) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.60934" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "speed" }
     ]
    }
   ]
  },
  {
   "title": "Power Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "select cumulative_sum(psum)/1000 from (SELECT sum(\"power\") as psum FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND power > 0 AND $timeFilter GROUP BY time(3600s) fill(0))",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "vehicle_state",
     "query": "SELECT last(\"odometer\") * $rangefactor FROM \"vehicle_state\" WHERE (\"metric\" = 'odometer') ",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Outside Temperatur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "outside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$tempfactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Inside Temperatur",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "inside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$tempfactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Chargelimit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charge_limit_soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Battery Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "kwatt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT last(\"power\") FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Revenue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "power",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "query": "SELECT mean(\"power\") FROM \"drive_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "odometer vs range",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "odometer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle_state",
     "query": "SELECT -mean(\"odometer\") *$rangefactor FROM \"vehicle_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "bat range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Efficiency in numbers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "odometer increase",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vehicle_state",
     "query": "SELECT (last(\"odometer\") - first(\"odometer\")) *$rangefactor FROM \"vehicle_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "battery range decrease",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (first(\"battery_range\") - last(\"battery_range\")) *$rangefactor FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Drive Mode",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "drive_state",
     "query": "SELECT \"shift_state\" FROM \"drive_state\" WHERE (\"metric\" = 'shift_state' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "shift_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Various States",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Vehicle Connection State",
     "measurement": "vehicle_state",
     "query": "SELECT \"state\" FROM \"vehicle_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter-5d\n",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "state" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Batteryheater State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"battery_heater_on\" FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sentry Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vehicle_state",
     "query": "SELECT \"sentry_mode\" FROM \"vehicle_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sentry_mode" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  { "title": "Charging $vehicle_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "vehicle_name" },
  {
   "title": "Current Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "ideal_battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Voltage",
   "type": "singlestat",
   "description": "Voltage supplied by Charger",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 25 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"charger_voltage\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) ",
     "select": [
      [
       { "params": [ "charger_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "charger_voltage" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Voltage and Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"battery_range\") *$rangefactor FROM \"charge_state\" WHERE (\"metric\" = 'battery_range') AND $timeFilter",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"est_battery_range\") FROM \"charge_state\" WHERE (\"metric\" = 'est_battery_range')  AND $timeFilter",
     "select": [
      [
       { "params": [ "est_battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "Ulysses" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "singlestat",
   "description": "Current Battery Level",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 30 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Battery Level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": "SELECT mean(\"battery_level\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Chargelimit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": "SELECT mean(\"charge_limit_soc\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "charge_limit_soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Battery Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": "SELECT mean(\"battery_level\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "AC Charger Actual Current",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
   "format": "amp",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_actual_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "AC Charger Phases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_phases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy added",
   "type": "singlestat",
   "description": "Energy added on last Charge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 35 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"charge_energy_added\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND charge_energy_added > 0",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Power",
   "type": "singlestat",
   "description": "Power supplied by Charger.",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 35 },
   "format": "kwatt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "AC Charger Current",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Current Requested",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charge_current_request" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Current Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_actual_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last charge finished",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 37 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"charge_energy_added\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND charge_energy_added>0 ",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Time to Full at current Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "time_to_full_charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Projected Range ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Projected 100% Range (rated)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": " select ((BR/BL)*100*$rangefactor) from (select mean(battery_range) as BR ,mean(battery_level) as BL from charge_state group by time($__interval) fill(linear)) ",
     "select": [
      [
       { "params": [ "est_battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "Projected 100% Range (est)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " select ((BR/BL)*100*$rangefactor) from (select mean(est_battery_range) as BR ,mean(battery_level) as BL from charge_state group by time($__interval) fill(linear)) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Projected 100% Range (ideal)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " select ((BR/BL)*100*$rangefactor) from (select mean(ideal_battery_range) as BR ,mean(battery_level) as BL from charge_state group by time($__interval) fill(linear)) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Environment $vehicle_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "FAN Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "fan_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "fan_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "inside_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "inside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "outside_temp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "climate_state",
     "select": [
      [
       { "params": [ "outside_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Left",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_left" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Steering Wheel",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT last(\"steering_wheel_heater\") FROM \"climate_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "steering_wheel_heater" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Right",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_right" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Left",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_left" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Center",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_center" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Seat Heater :: Rear Right",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "climate_state",
     "query": "SELECT \"value\" FROM \"climate_state\" WHERE (\"metric\" = 'seat_heater_right' AND \"display_name\" =~ /^$vehicle_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "seat_heater_rear_right" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Windows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "front driver",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "fd_window" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "front passenger",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "fp_window" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "rear driver",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "rd_window" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "rear passenger",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "rp_window" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Doors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "front driver",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "df" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "front passenger",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "pf" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "rear driver",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "rear passenger",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "pr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "rear trunk",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "rt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "front trunk",
     "measurement": "vehicle_state",
     "select": [
      [
       { "params": [ "ft" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}